### ISSUE TITLE
Is this still working

### ISSUE THREAD

**Issue by cinter** [ThatGuySam/vimeo-thumbnail-server#10]
Does vumbnail.com still work with newly uploaded videos? I'm having some trouble with it.

**Comment by cinter** [comment]
@ThatGuySam

**Comment by ThatGuySam** [comment]
Hey @cinter, 

I'm not able to view that video. Can you double-check your privacy settings. 

<img width="1680" alt="Screen Shot 2022-01-20 at 12 16 57 PM" src="https://user-images.githubusercontent.com/2830379/150397883-e1fa0def-90e7-42c4-b27b-99a7e04295b0.png">

**Comment by cinter** [comment]
I had the video set to "hidden from Vimeo, embeddable anywhere", I set it to public now, and it works!

Sorry, didn't mean to waste your time!

**Comment by ThatGuySam** [comment]
All good! Good luck on your coding adventures
