### ISSUE TITLE
Is vumbnail.com production site or sample demonstration site?

### ISSUE THREAD

**Issue by Atr07** [ThatGuySam/vimeo-thumbnail-server#6]
Can I use vumbnail.com in production or should I need to host repo on my own server and use that?

**Comment by ThatGuySam** [comment]
Vumbnail currently serves about 2.8 million requests per month. 

Although it was originally designed to help developers with a specific problem the infrastructure I built has held up nicely so I would say it's pretty safe to use on a production site. 

However, if you're running a project that absolutely has to be running on your own company's hosting you're welcome to fork the repo and deploy it to Vercel as it is an open-source project.
